export const words = [
  {en:"afraid", ru:"боящийся"},
  {en:"angry", ru:"злой"},
  {en:"annoyed", ru:"раздосадованный"},
  {en:"antique shop", ru:"антикварный магазин"},
  {en:"bad-tempered", ru:"раздражительный"},
  {en:"(to) become", ru:"становиться"},
  {en:"bored", ru:"скучающий"},
  {en:"boring", ru:"скучный"},
  {en:"boyfriend", ru:"любимый парень"},
  {en:"disappointed", ru:"разочарованный"},
  {en:"easygoing", ru:"покладистый, благодушный"},
  {en:"engineer", ru:"инженер"},
  {en:"excited", ru:"возбужденный, взволнованный"},
  {en:"generous", ru:"щедрый"},
  {en:"(to) grow up", ru:"вырасти "},
  {en:"in a hurry", ru:"в спешке"},
  {en:"be (was, were, been)", ru:"быть, являться"},
  {en:"become (became, become)", ru:"становиться"},
  {en:"begin (began, begun)", ru:"начинать"},
  {en:"build (built, built)", ru:"строить"},
  {en:"buy (bought, bought)", ru:"покупать"},
  {en:"come (came, come)", ru:"приходить"},
  {en:"do (did, done)", ru:"делать,  выполнять"},
  {en:"drive (drove, driven)", ru:"ездить"},
  {en:"eat (ate, eaten)", ru:"есть,  поглощать"},
  {en:"fall (fell, fallen)", ru:"падать"},
  {en:"give (gave, given)", ru:"дать, подать"},
  {en:"lay (laid, laid)", ru:"класть, положить"},
  {en:"lead (led, led)", ru:"сопровождать, руководить"},
  {en:"lose (lost, lost)", ru:"терять, лишаться"},
  {en:"mean (meant, meant)", ru:"значить, иметь в виду"},
  {en:"(to) keep", ru:"оставлять себе"},
  {en:"(to) lie", ru:"лежать"},
  {en:"mall", ru:"комплекс магазинов"},
  {en:"nervous", ru:"нервный"},
  {en:"paint", ru:"красить"},
  {en:"(to) pass", ru:"сдавать"},
  {en:"postcard", ru:"открытка"},
  {en:"potatoes", ru:"картофель"},
  {en:"present", ru:"подарок"},
  {en:"relaxed", ru:"расслабленный"},
  {en:"selfish", ru:"эгоистичный"},
  {en:"(to) serve", ru:"подавать на стол"},
  {en:"shy", ru:"стеснительный"},
  {en:"sick", ru:"больной"},
  {en:"(to) slip", ru:"поскользнуться"},
  {en:"small", ru:"маленький"},
  {en:"soccer", ru:"футбол"},
  {en:"(to) stay calm", ru:"быть спокойным"},
  {en:"subject", ru:"изучаемый предмет"},
  {en:"(to) talk", ru:"разговаривать"},
  {en:"tired", ru:"уставший"},
  {en:"toy", ru:"игрушка"},
  {en:"vacation", ru:"отпуск"},
  {en:"village", ru:"деревня"},
  {en:"waitress", ru:"официантка"},
  {en:"water", ru:"вода"},
  {en:"(to) wear", ru:"носить"},
  {en:"(to) yell", ru:"кричать"},
  {en: "iritated", ru: "раздраженный"},
  {en: "bite (bit,bitten)", ru: "кусать"},
  {en: "blow (blew,blown)", ru: "дуть,выдыхать"},
  {en: "break (broke,broken)", ru: "ломать,разбивать"},
  {en: "bring (brought,brought)", ru: "приносить,привозить"},
  {en: "catch (caught,caught)", ru: "ловить,поймать"},
  {en: "choose (chose,chosen)", ru: "выбирать,избирать"},
  {en: "cost (cost,cost)", ru: "стоить,обходиться"},
  {en: "cut (cut,cut)", ru: "резать,разрезать"},
  {en: "deal (dealt,dealt)", ru: "иметь дело,распределять"},
  {en: "dig (dug,dug)", ru: "копать,рыть"},
  {en: "draw (drew,drawn)", ru: "рисовать,чертить"},
  {en: "drink (drank,drunk)", ru: "пить"},
  {en: "feed (fed,fed)", ru: "кормить"},
  {en: "fight (fought,fought)", ru: "драться,сражаться"},
  {en: "find (found,found)", ru: "находить,обнаруживать"},
  {en: "fly (flew,flown)", ru: "летать"},
  {en: "forget (forgot,forgotten)", ru: "забывать о (чём-либо)"},
  {en: "forgive (forgave,forgiven)", ru: "прощать"},
  {en: "get (got,got)", ru: "получать,добираться"},
  {en: "go (went,gone)", ru: "идти,двигаться"},
  {en: "grow (grew,grown)", ru: "расти,вырастать"},
  {en: "hang (hung,hung)", ru: "вешать,развешивать"},
  {en: "have (had,had)", ru: "иметь, обладать"},
  {en: "hear (heard,heard)", ru: "слышать, услышать"},
  {en: "hide (hid,hidden)", ru: "прятать, скрывать"},
  {en: "hit (hit,hit)", ru: "ударять, поражать"},
  {en: "hold (held,held)", ru: "держать, удерживать"},
  {en: "hurt (hurt,hurt)", ru: "ранить, причинять боль"},
  {en: "keep (kept,kept)", ru: "хранить, сохранять"},
  {en: "leave (left,left)", ru: "покидать, уходить"},
  {en: "lend (lent,lent)", ru: "одалживать, давать взаймы"},
  {en: "let (let,let)", ru: "позволять, разрешать"},
  {en: "lie (lay,lain)", ru: "лежать"},
  {en: "make (made,made)", ru: "делать, создавать"},
  {en: "meet (met,met)", ru: "встречать, знакомиться"},
  {en: "pay (paid,paid)", ru: "платить, оплачивать"},
  {en: "put (put,put)", ru: "ставить, класть"},
  {en: "read (read,read)", ru: "читать, прочитать"},
  {en: "ride (rode,ridden)", ru: "ехать верхом, кататься"},
  {en: "ring (rang,rung)", ru: "звенеть, звонить"},
  {en: "rise (rose,risen)", ru: "вставать, подниматься"},
  {en: "run (ran,run)", ru: "бежать, бегать"},
  {en: "say (said,said)", ru: "говорить, сказать"},
  {en: "see (saw,seen)", ru: "видеть"},
  {en: "sell (sold,sold)", ru: "продавать, торговать"},
  {en: "send (sent,sent)", ru: "посылать, отправлять"},
  {en: "set (set,set)", ru: "устанавливать, задавать"},
  {en: "shake (shook,shaken)", ru: "трясти, встряхивать"},
  {en: "shine (shone,shone)", ru: "светить, сиять"},
  {en: "show (showed,shown)", ru: "показывать"},
  {en: "shut (shut,shut)", ru: "закрывать, запирать"},
  {en: "sing (sang,sung)", ru: "петь, напевать"},
  {en: "sit (sat,sat)", ru: "сидеть, садиться"},
  {en: "sleep (slept,slept)", ru: "спать"},
  {en: "speak (spoke,spoken)", ru: "говорить, разговаривать"},
  {en: "spend (spent,spent)", ru: "тратить, расходовать"},
  {en: "stand (stood,stood)", ru: "стоять"},
  {en: "steal (stole,stolen)", ru: "воровать, красть"},
  {en: "swear (swore,swore)", ru: "клясться, присягать"},
  {en: "sweep (swept,swept)", ru: "мести, подметать"},
  {en: "swim (swam,swum)", ru: "плавать, плыть"},
  {en: "take (took,taken)", ru: "брать, хватать"},
  {en: "teach (taught,taught)", ru: "учить, обучать"},
  {en: "tear (tore,torn)", ru: "рвать, отрывать"},
  {en: "tell (told,told)", ru: "рассказывать"},
  {en: "think (thought,thought)", ru: "думать, мыслить"},
  {en: "throw (threw,thrown)", ru: "бросать, кидать"},
  {en: "understand (understood,understood)", ru: "понимать, постигать"},
  {en: "wake (woke,woken)", ru: "просыпаться, будить"},
  {en: "wear (wore,worn)", ru: "носить (одежду)"},
  {en: "win (won,won)", ru: "победить, выиграть"},
  {en: "wind (wound,wound)", ru: "наматывать,заводить"},
]