export default words = [
  {en: 'be', ru: 'быть'}
  {en: 'have', ru: 'иметь'}
  {en: 'do', ru: 'делать'}
  {en: 'say', ru: 'говорить'}
  {en: 'go', ru: 'идти'}
  {en: 'get', ru: 'получать'}
  {en: 'make', ru: 'делать'}
  {en: 'know', ru: 'знать'}
  {en: 'think', ru: 'думать'}
  {en: 'take', ru: 'брать'}
  {en: 'see', ru: 'видеть'}
  {en: 'come', ru: 'приходить'}
  {en: 'want', ru: 'хотеть'}
  {en: 'use', ru: 'использовать'}
  {en: 'find', ru: 'находить'}
  {en: 'give', ru: 'давать'}
  {en: 'tell', ru: 'рассказывать'}
  {en: 'work', ru: 'работать'}
  {en: 'call', ru: 'звонить'}
  {en: 'try', ru: 'пытаться'}
  {en: 'ask', ru: 'спрашивать'}
  {en: 'need', ru: 'нуждаться'}
  {en: 'feel', ru: 'чувствовать'}
  {en: 'become', ru: 'становиться'}
  {en: 'leave', ru: 'оставлять'}
  {en: 'put', ru: 'класть'}
  {en: 'mean', ru: 'значить'}
  {en: 'keep', ru: 'хранить'}
  {en: 'let', ru: 'позволять'}
  {en: 'begin', ru: 'начинать'}
  {en: 'seem', ru: 'казаться'}
  {en: 'help', ru: 'помогать'}
  {en: 'show', ru: 'показывать'}
  {en: 'hear', ru: 'слышать'}
  {en: 'play', ru: 'играть'}
  {en: 'run', ru: 'бежать'}
  {en: 'move', ru: 'двигаться'}
  {en: 'live', ru: 'жить'}
  {en: 'believe', ru: 'верить'}
  {en: 'bring', ru: 'приносить'}
  {en: 'happen', ru: 'случаться'}
  {en: 'write', ru: 'писать'}
  {en: 'sit', ru: 'сидеть'}
  {en: 'stand', ru: 'стоять'}
  {en: 'lose', ru: 'терять'}
  {en: 'pay', ru: 'платить'}
  {en: 'meet', ru: 'встречать'}
  {en: 'include', ru: 'включать'}
  {en: 'continue', ru: 'продолжать'}
  {en: 'set', ru: 'устанавливать'}
]